---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-service
  labels:
    app: redis-test-service
    env: test
    username: osvasali
spec:
  type: ClusterIP
  selector:
    app: hw6-osvasali-test-redis
    name: database
    env: test
    username: osvasali
  ports:
  - name: hw6-test
    port: 6427
    targetPort: 6379[osvasali@kube-2 06]$ ^C
[osvasali@kube-2 06]$ cat deployment-python-debug.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-debug-deployment
  labels:
    app: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py39
          image: python:3.9
          command: ['sleep', '999999999']
