---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-service
  labels:
    app: hw6-osvasali-test-redis
    env: test
    username: osvasali
spec:
  type: ClusterIP
  selector:
    app: hw6-osvasali-test-redis
  ports:
  - name: hw6-osvasali-test-redis
    port: 6379
    targetPort: 6379
