---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-test-volume
  labels:
    app: hw6-test
    env: test
    username: osvasali
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
