---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-service
  labels:
    app: redis-test-service
    env: test
    username: osvasali
spec:
  type: ClusterIP
  selector:
    app: hw6-osvasali-test-redis
    name: database
    env: test
    username: osvasali
  ports:
  - name: hw6-test
    port: 6427
    targetPort: 6379
