---
apiVersion: v1
kind: Service
metadata:
  name: hw6-flask-test-service
  labels:
    app: hw6-flask-test-service
    env: test
    username: osvasali
spec:
  type: ClusterIP
  selector:
    app: hw6-test-flask
    name: hw6-countainer-flask
    env: test
    username: osvasali
  ports:
  - name: hw6-test
    port: 5027
    targetPort: 5000
